// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pos.Domain.Persistence;

#nullable disable

namespace Pos.Domain.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260729015645_AddOrderItemVatFields")]
    partial class AddOrderItemVatFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pos.Domain.Entities.Attendance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ClockIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ClockOut")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Attendances");

                    b.HasData(
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888801"),
                            ClockIn = new DateTime(2026, 7, 25, 6, 8, 0, 0, DateTimeKind.Utc),
                            ClockOut = new DateTime(2026, 7, 25, 14, 2, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("33333333-3333-3333-3333-333333333334")
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888802"),
                            ClockIn = new DateTime(2026, 7, 25, 14, 14, 0, 0, DateTimeKind.Utc),
                            ClockOut = new DateTime(2026, 7, 25, 22, 5, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("33333333-3333-3333-3333-333333333303")
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888803"),
                            ClockIn = new DateTime(2026, 7, 25, 5, 54, 0, 0, DateTimeKind.Utc),
                            ClockOut = new DateTime(2026, 7, 25, 14, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("33333333-3333-3333-3333-333333333302")
                        });
                });

            modelBuilder.Entity("Pos.Domain.Entities.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-a111-a111-a111-a11111111111"),
                            Address = "123 Main Street, Bangkok",
                            Code = "BR001",
                            Name = "Head Office Branch"
                        },
                        new
                        {
                            Id = new Guid("a2222222-a222-a222-a222-a22222222222"),
                            Address = "991 Rama I Rd, Bangkok",
                            Code = "35",
                            Name = "Siam Paragon Branch"
                        });
                });

            modelBuilder.Entity("Pos.Domain.Entities.CashierShift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ActualCashCounted")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("CashDifference")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CashierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CloseNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ExpectedCash")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OpeningCash")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PosTerminalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalCashPaidIn")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalCashPaidOut")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalSystemCashSales")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CashierId");

                    b.ToTable("CashierShifts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ee111111-1111-1111-1111-111111111101"),
                            ActualCashCounted = 450.00m,
                            BranchId = new Guid("a1111111-a111-a111-a111-a11111111111"),
                            CashDifference = 0.00m,
                            CashierId = new Guid("33333333-3333-3333-3333-333333333334"),
                            ClosedAt = new DateTime(2026, 7, 25, 14, 0, 0, 0, DateTimeKind.Utc),
                            ExpectedCash = 450.00m,
                            OpenedAt = new DateTime(2026, 7, 25, 6, 0, 0, 0, DateTimeKind.Utc),
                            OpeningCash = 100.00m,
                            PosTerminalId = "term-1",
                            Status = "Closed",
                            TotalCashPaidIn = 0.00m,
                            TotalCashPaidOut = 0.00m,
                            TotalSystemCashSales = 350.00m
                        },
                        new
                        {
                            Id = new Guid("ee111111-1111-1111-1111-111111111102"),
                            BranchId = new Guid("a1111111-a111-a111-a111-a11111111111"),
                            CashierId = new Guid("33333333-3333-3333-3333-333333333303"),
                            ExpectedCash = 220.00m,
                            OpenedAt = new DateTime(2026, 7, 25, 14, 0, 0, 0, DateTimeKind.Utc),
                            OpeningCash = 100.00m,
                            PosTerminalId = "term-1",
                            Status = "Open",
                            TotalCashPaidIn = 0.00m,
                            TotalCashPaidOut = 0.00m,
                            TotalSystemCashSales = 120.00m
                        });
                });

            modelBuilder.Entity("Pos.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222201"),
                            Code = "APP",
                            IsActive = true,
                            Name = "Appetizers"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222202"),
                            Code = "MAIN",
                            IsActive = true,
                            Name = "Main Course"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222203"),
                            Code = "BEV",
                            IsActive = true,
                            Name = "Beverages"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222204"),
                            Code = "DES",
                            IsActive = true,
                            Name = "Desserts"
                        });
                });

            modelBuilder.Entity("Pos.Domain.Entities.Coupon", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApplicableProductIdsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscountValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MaxDiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinOrderAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UsageLimit")
                        .HasColumnType("int");

                    b.Property<int>("UsedCount")
                        .HasColumnType("int");

                    b.HasKey("Code");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            Code = "WELCOME10",
                            ApplicableProductIdsJson = "[]",
                            Description = "10% Welcome Discount",
                            DiscountType = "Percentage",
                            DiscountValue = 10m,
                            EndDate = new DateTime(2026, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MaxDiscountAmount = 15.0m,
                            MinOrderAmount = 20.0m,
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UsageLimit = 1000,
                            UsedCount = 42
                        },
                        new
                        {
                            Code = "FLASH5",
                            ApplicableProductIdsJson = "[]",
                            Description = "$5 off on order above $30",
                            DiscountType = "Fixed",
                            DiscountValue = 5.0m,
                            EndDate = new DateTime(2026, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MaxDiscountAmount = 5.0m,
                            MinOrderAmount = 30.0m,
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UsageLimit = 500,
                            UsedCount = 18
                        },
                        new
                        {
                            Code = "VIPBURGER",
                            ApplicableProductIdsJson = "[]",
                            Description = "20% off on Burger combos",
                            DiscountType = "Percentage",
                            DiscountValue = 20m,
                            EndDate = new DateTime(2026, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MaxDiscountAmount = 10.0m,
                            MinOrderAmount = 15.0m,
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UsageLimit = 100,
                            UsedCount = 5
                        });
                });

            modelBuilder.Entity("Pos.Domain.Entities.CouponUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CouponCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UsedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("CouponUsages");
                });

            modelBuilder.Entity("Pos.Domain.Entities.DrawerDropTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ApprovedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DrawerDropTransactions");
                });

            modelBuilder.Entity("Pos.Domain.Entities.DrawerOpenLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CashierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PosTerminalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("DrawerOpenLogs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cc111111-1111-1111-1111-111111111101"),
                            ApprovedBy = new Guid("33333333-3333-3333-3333-333333333302"),
                            BranchId = new Guid("a1111111-a111-a111-a111-a11111111111"),
                            CashierId = new Guid("33333333-3333-3333-3333-333333333334"),
                            OpenedAt = new DateTime(2026, 7, 25, 9, 30, 0, 0, DateTimeKind.Utc),
                            PosTerminalId = "term-1",
                            Reason = "NO_SALE",
                            ShiftId = new Guid("44444444-4444-4444-4444-444444444401")
                        },
                        new
                        {
                            Id = new Guid("cc111111-1111-1111-1111-111111111102"),
                            BranchId = new Guid("a1111111-a111-a111-a111-a11111111111"),
                            CashierId = new Guid("33333333-3333-3333-3333-333333333303"),
                            OpenedAt = new DateTime(2026, 7, 25, 15, 45, 0, 0, DateTimeKind.Utc),
                            PosTerminalId = "term-1",
                            Reason = "MANUAL_OPEN",
                            ShiftId = new Guid("44444444-4444-4444-4444-444444444403")
                        });
                });

            modelBuilder.Entity("Pos.Domain.Entities.LeaveRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LeaveType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LeaveRequests");

                    b.HasData(
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999901"),
                            CreatedAt = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            LeaveType = "SickLeave",
                            Reason = "High fever and flu",
                            StartDate = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Approved",
                            UserId = new Guid("33333333-3333-3333-3333-333333333304")
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999902"),
                            CreatedAt = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateTime(2026, 8, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            LeaveType = "AnnualLeave",
                            Reason = "Family vacation",
                            StartDate = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Approved",
                            UserId = new Guid("33333333-3333-3333-3333-333333333334")
                        });
                });

            modelBuilder.Entity("Pos.Domain.Entities.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PointsBalance")
                        .HasColumnType("int");

                    b.Property<string>("TierLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalSpent")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MemberNo")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1111111-d111-d111-d111-d11111111111"),
                            CreatedAt = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sarah.j@example.com",
                            FullName = "Sarah Jenkins",
                            MemberNo = "M-1001",
                            PhoneNumber = "0812345678",
                            PointsBalance = 540,
                            TierLevel = "Gold",
                            TotalSpent = 1200.00m
                        },
                        new
                        {
                            Id = new Guid("d2222222-d222-d222-d222-d22222222222"),
                            CreatedAt = new DateTime(2023, 11, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "alex.r@example.com",
                            FullName = "Alex Rivera",
                            MemberNo = "M-1002",
                            PhoneNumber = "0898765432",
                            PointsBalance = 1250,
                            TierLevel = "Platinum",
                            TotalSpent = 4500.00m
                        });
                });

            modelBuilder.Entity("Pos.Domain.Entities.MemberAiRecommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DiscountOfferPercent")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RecommendationReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RecommendedProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("RecommendedProductId");

                    b.ToTable("MemberAiRecommendations");
                });

            modelBuilder.Entity("Pos.Domain.Entities.MemberPromotion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("FreeProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FreeQuantity")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MinQuantity")
                        .HasColumnType("int");

                    b.Property<decimal>("MinSpentAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PromotionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FreeProductId");

                    b.ToTable("MemberPromotions");
                });

            modelBuilder.Entity("Pos.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AmountBeforeVat")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CashierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CouponDiscount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("GrandTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HmacSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OrderNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PosTerminalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SubTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalItemDiscount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VatAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("MemberId");

                    b.HasIndex("OrderNo")
                        .IsUnique();

                    b.HasIndex("SyncStatus");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Pos.Domain.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ItemDiscount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VatAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Pos.Domain.Entities.OrderPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderPayments");
                });

            modelBuilder.Entity("Pos.Domain.Entities.PosTerminal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TerminalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId", "TerminalId")
                        .IsUnique();

                    b.ToTable("PosTerminals");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1111111-c111-c111-c111-c11111111111"),
                            BranchId = new Guid("a1111111-a111-a111-a111-a11111111111"),
                            Name = "Head Office Terminal 1",
                            TerminalId = "N01"
                        },
                        new
                        {
                            Id = new Guid("c1111111-c111-c111-c111-c11111111112"),
                            BranchId = new Guid("a1111111-a111-a111-a111-a11111111111"),
                            Name = "Head Office Terminal 2",
                            TerminalId = "N02"
                        },
                        new
                        {
                            Id = new Guid("c2222222-c222-c222-c222-c22222222221"),
                            BranchId = new Guid("a2222222-a222-a222-a222-a22222222222"),
                            Name = "Siam Paragon Terminal 1",
                            TerminalId = "N02"
                        },
                        new
                        {
                            Id = new Guid("c2222222-c222-c222-c222-c22222222222"),
                            BranchId = new Guid("a2222222-a222-a222-a222-a22222222222"),
                            Name = "Siam Paragon Terminal 2",
                            TerminalId = "N03"
                        });
                });

            modelBuilder.Entity("Pos.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVatInclusive")
                        .HasColumnType("bit");

                    b.Property<int>("MinStockThreshold")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StandardCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111101"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222201"),
                            Code = "0012",
                            IsActive = true,
                            IsVatInclusive = true,
                            MinStockThreshold = 10,
                            Name = "Mediterranean Salad",
                            Price = 14.50m,
                            StandardCost = 5.00m,
                            StockQuantity = 35,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111102"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222202"),
                            Code = "0054",
                            IsActive = true,
                            IsVatInclusive = true,
                            MinStockThreshold = 15,
                            Name = "Signature Burger",
                            Price = 18.00m,
                            StandardCost = 6.50m,
                            StockQuantity = 42,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111103"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222203"),
                            Code = "0098",
                            IsActive = true,
                            IsVatInclusive = true,
                            MinStockThreshold = 20,
                            Name = "Artisan Latte",
                            Price = 5.25m,
                            StandardCost = 1.50m,
                            StockQuantity = 80,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111104"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222204"),
                            Code = "0112",
                            IsActive = true,
                            IsVatInclusive = true,
                            MinStockThreshold = 12,
                            Name = "Glazed Donut",
                            Price = 3.50m,
                            StandardCost = 1.00m,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111105"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222202"),
                            Code = "0087",
                            IsActive = true,
                            IsVatInclusive = true,
                            MinStockThreshold = 8,
                            Name = "Mixed Grill",
                            Price = 24.00m,
                            StandardCost = 9.00m,
                            StockQuantity = 3,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111106"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222201"),
                            Code = "0041",
                            IsActive = true,
                            IsVatInclusive = true,
                            MinStockThreshold = 15,
                            Name = "Truffle Fries",
                            Price = 8.50m,
                            StandardCost = 2.50m,
                            StockQuantity = 65,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111107"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222203"),
                            Code = "0203",
                            IsActive = true,
                            IsVatInclusive = true,
                            MinStockThreshold = 10,
                            Name = "Iced Matcha Latte",
                            Price = 6.00m,
                            StandardCost = 2.00m,
                            StockQuantity = 2,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111108"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222202"),
                            Code = "0319",
                            IsActive = true,
                            IsVatInclusive = true,
                            MinStockThreshold = 12,
                            Name = "Ribeye Steak 300g",
                            Price = 38.00m,
                            StandardCost = 15.00m,
                            StockQuantity = 4,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Version = 1
                        });
                });

            modelBuilder.Entity("Pos.Domain.Entities.ProductAssociation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ConfidenceScore")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PrimaryProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RecommendedProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryProductId");

                    b.HasIndex("RecommendedProductId");

                    b.ToTable("ProductAssociations");
                });

            modelBuilder.Entity("Pos.Domain.Entities.PublicHoliday", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("HolidayDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PayMultiplier")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("PublicHolidays");
                });

            modelBuilder.Entity("Pos.Domain.Entities.PurchaseOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PoNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("ProposedByVendor")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PoNumber")
                        .IsUnique();

                    b.HasIndex("VendorId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("PurchaseOrders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666601"),
                            CreatedAt = new DateTime(2026, 7, 25, 8, 30, 0, 0, DateTimeKind.Utc),
                            PoNumber = "PO-20260725-01",
                            ProposedByVendor = true,
                            Status = "Proposed",
                            TotalAmount = 54.00m,
                            VendorId = new Guid("d1111111-d111-d111-d111-d11111111111"),
                            WarehouseId = new Guid("b1111111-b111-b111-b111-b11111111111")
                        });
                });

            modelBuilder.Entity("Pos.Domain.Entities.PurchaseOrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("PurchaseOrderItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666602"),
                            ProductId = new Guid("11111111-1111-1111-1111-111111111102"),
                            PurchaseOrderId = new Guid("66666666-6666-6666-6666-666666666601"),
                            Quantity = 3,
                            SubTotal = 54.00m,
                            UnitPrice = 18.00m
                        });
                });

            modelBuilder.Entity("Pos.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Cashier"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "BranchManager"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Name = "Accountant"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Name = "Vendor"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Name = "PurchaserManager"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Name = "StockClerk"
                        });
                });

            modelBuilder.Entity("Pos.Domain.Entities.RoleChangeAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ChangedByAdminId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NewRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OldRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TargetUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("RoleChangeAuditLogs");
                });

            modelBuilder.Entity("Pos.Domain.Entities.RoleRoutePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAllowed")
                        .HasColumnType("bit");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoutePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleRoutePermissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aa111111-1111-1111-1111-111111111101"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAllowed = true,
                            RoleId = new Guid("22222222-2222-2222-2222-222222222222"),
                            RoutePath = "/pos"
                        },
                        new
                        {
                            Id = new Guid("aa111111-1111-1111-1111-111111111102"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAllowed = true,
                            RoleId = new Guid("22222222-2222-2222-2222-222222222222"),
                            RoutePath = "/shifts"
                        },
                        new
                        {
                            Id = new Guid("aa111111-1111-1111-1111-111111111103"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAllowed = true,
                            RoleId = new Guid("22222222-2222-2222-2222-222222222222"),
                            RoutePath = "/profile"
                        },
                        new
                        {
                            Id = new Guid("aa111111-1111-1111-1111-111111111104"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAllowed = true,
                            RoleId = new Guid("33333333-3333-3333-3333-333333333333"),
                            RoutePath = "/pos"
                        },
                        new
                        {
                            Id = new Guid("aa111111-1111-1111-1111-111111111105"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAllowed = true,
                            RoleId = new Guid("33333333-3333-3333-3333-333333333333"),
                            RoutePath = "/shifts"
                        },
                        new
                        {
                            Id = new Guid("aa111111-1111-1111-1111-111111111106"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAllowed = true,
                            RoleId = new Guid("33333333-3333-3333-3333-333333333333"),
                            RoutePath = "/reports"
                        },
                        new
                        {
                            Id = new Guid("aa111111-1111-1111-1111-111111111107"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAllowed = true,
                            RoleId = new Guid("33333333-3333-3333-3333-333333333333"),
                            RoutePath = "/profile"
                        },
                        new
                        {
                            Id = new Guid("aa111111-1111-1111-1111-111111111108"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAllowed = true,
                            RoleId = new Guid("44444444-4444-4444-4444-444444444444"),
                            RoutePath = "/reports"
                        },
                        new
                        {
                            Id = new Guid("aa111111-1111-1111-1111-111111111109"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAllowed = true,
                            RoleId = new Guid("44444444-4444-4444-4444-444444444444"),
                            RoutePath = "/vendor"
                        },
                        new
                        {
                            Id = new Guid("aa111111-1111-1111-1111-111111111110"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAllowed = true,
                            RoleId = new Guid("44444444-4444-4444-4444-444444444444"),
                            RoutePath = "/profile"
                        },
                        new
                        {
                            Id = new Guid("aa111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAllowed = true,
                            RoleId = new Guid("55555555-5555-5555-5555-555555555555"),
                            RoutePath = "/vendor"
                        },
                        new
                        {
                            Id = new Guid("aa111111-1111-1111-1111-111111111112"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAllowed = true,
                            RoleId = new Guid("55555555-5555-5555-5555-555555555555"),
                            RoutePath = "/profile"
                        },
                        new
                        {
                            Id = new Guid("aa111111-1111-1111-1111-111111111113"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAllowed = true,
                            RoleId = new Guid("66666666-6666-6666-6666-666666666666"),
                            RoutePath = "/vendor"
                        },
                        new
                        {
                            Id = new Guid("aa111111-1111-1111-1111-111111111114"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAllowed = true,
                            RoleId = new Guid("66666666-6666-6666-6666-666666666666"),
                            RoutePath = "/inventory"
                        },
                        new
                        {
                            Id = new Guid("aa111111-1111-1111-1111-111111111115"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAllowed = true,
                            RoleId = new Guid("66666666-6666-6666-6666-666666666666"),
                            RoutePath = "/profile"
                        },
                        new
                        {
                            Id = new Guid("aa111111-1111-1111-1111-111111111116"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAllowed = true,
                            RoleId = new Guid("77777777-7777-7777-7777-777777777777"),
                            RoutePath = "/inventory"
                        },
                        new
                        {
                            Id = new Guid("aa111111-1111-1111-1111-111111111117"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAllowed = true,
                            RoleId = new Guid("77777777-7777-7777-7777-777777777777"),
                            RoutePath = "/profile"
                        },
                        new
                        {
                            Id = new Guid("aa111111-1111-1111-1111-111111111118"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAllowed = true,
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RoutePath = "/pos"
                        },
                        new
                        {
                            Id = new Guid("aa111111-1111-1111-1111-111111111119"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAllowed = true,
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RoutePath = "/shifts"
                        },
                        new
                        {
                            Id = new Guid("aa111111-1111-1111-1111-111111111120"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAllowed = true,
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RoutePath = "/shifts/schedule"
                        },
                        new
                        {
                            Id = new Guid("aa111111-1111-1111-1111-111111111121"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAllowed = true,
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RoutePath = "/vendor"
                        },
                        new
                        {
                            Id = new Guid("aa111111-1111-1111-1111-111111111122"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAllowed = true,
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RoutePath = "/reports"
                        },
                        new
                        {
                            Id = new Guid("aa111111-1111-1111-1111-111111111123"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAllowed = true,
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RoutePath = "/admin/roles"
                        },
                        new
                        {
                            Id = new Guid("aa111111-1111-1111-1111-111111111124"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAllowed = true,
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RoutePath = "/profile"
                        });
                });

            modelBuilder.Entity("Pos.Domain.Entities.ShiftSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoleInShift")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShiftTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("WorkDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ShiftTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("ShiftSchedules");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444401"),
                            BranchId = new Guid("a1111111-a111-a111-a111-a11111111111"),
                            RoleInShift = "Cashier",
                            ShiftTypeId = 1,
                            Status = "Scheduled",
                            UserId = new Guid("33333333-3333-3333-3333-333333333334"),
                            WorkDate = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444402"),
                            BranchId = new Guid("a1111111-a111-a111-a111-a11111111111"),
                            RoleInShift = "BranchManager",
                            ShiftTypeId = 1,
                            Status = "Scheduled",
                            UserId = new Guid("33333333-3333-3333-3333-333333333302"),
                            WorkDate = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444403"),
                            BranchId = new Guid("a1111111-a111-a111-a111-a11111111111"),
                            RoleInShift = "Cashier",
                            ShiftTypeId = 2,
                            Status = "Scheduled",
                            UserId = new Guid("33333333-3333-3333-3333-333333333303"),
                            WorkDate = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444404"),
                            BranchId = new Guid("a1111111-a111-a111-a111-a11111111111"),
                            RoleInShift = "Cashier",
                            ShiftTypeId = 3,
                            Status = "Scheduled",
                            UserId = new Guid("33333333-3333-3333-3333-333333333304"),
                            WorkDate = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Pos.Domain.Entities.ShiftSwapRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ManagerApprovedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RequestorShiftId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TargetShiftId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TargetUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RequestorShiftId");

                    b.ToTable("ShiftSwapRequests");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555501"),
                            CreatedAt = new DateTime(2026, 7, 25, 10, 30, 0, 0, DateTimeKind.Utc),
                            Reason = "Family emergency",
                            RequestorShiftId = new Guid("44444444-4444-4444-4444-444444444401"),
                            Status = "PendingPeer",
                            TargetUserId = new Guid("33333333-3333-3333-3333-333333333303")
                        });
                });

            modelBuilder.Entity("Pos.Domain.Entities.ShiftType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("ShiftTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndTime = new TimeSpan(0, 14, 0, 0, 0),
                            Name = "กะเช้า",
                            StartTime = new TimeSpan(0, 6, 0, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            EndTime = new TimeSpan(0, 22, 0, 0, 0),
                            Name = "กะบ่าย",
                            StartTime = new TimeSpan(0, 14, 0, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            EndTime = new TimeSpan(0, 6, 0, 0, 0),
                            Name = "กะดึก",
                            StartTime = new TimeSpan(0, 22, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("Pos.Domain.Entities.StockBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InitialQuantity")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RemainingQuantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("StockBatches");

                    b.HasData(
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777701"),
                            BatchNumber = "BATCH-INITIAL-01",
                            ExpiryDate = new DateTime(2027, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InitialQuantity = 50,
                            ProductId = new Guid("11111111-1111-1111-1111-111111111102"),
                            PurchaseOrderId = new Guid("00000000-0000-0000-0000-000000000000"),
                            ReceivedDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RemainingQuantity = 42,
                            UnitCost = 6.50m,
                            WarehouseId = new Guid("b1111111-b111-b111-b111-b11111111111")
                        });
                });

            modelBuilder.Entity("Pos.Domain.Entities.StockTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ChangeQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("StockTransactions");
                });

            modelBuilder.Entity("Pos.Domain.Entities.SystemAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HmacSignature")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("SystemAuditLogs");
                });

            modelBuilder.Entity("Pos.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("HourlyRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PinHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.HasIndex("VendorId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "System Administrator",
                            HourlyRate = 50.00m,
                            IsActive = true,
                            IsAdmin = true,
                            PasswordHash = "$2a$11$uC19S.8s3RpTb1hz7wKJouDpB766FnaRg500LzBhCb9rmVjsmSygu",
                            PinHash = "$2a$11$v.SpJbKinX0eR4gMp33utuzaMIvOIyPxJgyT78/e./y0kdFMQnrJS",
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333334"),
                            BranchId = new Guid("a1111111-a111-a111-a111-a11111111111"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Sarah Jenkins",
                            HourlyRate = 25.00m,
                            IsActive = true,
                            IsAdmin = false,
                            PasswordHash = "$2a$11$lndSqgQXC5RexO5S6cxWIu8ffjLPpcNR7xQQq41y9aouMf584wm2u",
                            PinHash = "$2a$11$Xkgs2dzU4n/gjcB4Y/NU5OSVM5ws31xKLgi/6k9JdP/xV46V7I7NO",
                            RoleId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Username = "sarah.jenkins"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333302"),
                            BranchId = new Guid("a1111111-a111-a111-a111-a11111111111"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Alex Rivera",
                            HourlyRate = 18.00m,
                            IsActive = true,
                            IsAdmin = false,
                            PasswordHash = "$2a$11$lndSqgQXC5RexO5S6cxWIu8ffjLPpcNR7xQQq41y9aouMf584wm2u",
                            PinHash = "$2a$11$Xkgs2dzU4n/gjcB4Y/NU5OSVM5ws31xKLgi/6k9JdP/xV46V7I7NO",
                            RoleId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Username = "alex.rivera"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333303"),
                            BranchId = new Guid("a1111111-a111-a111-a111-a11111111111"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Mark Tanaka",
                            HourlyRate = 20.00m,
                            IsActive = true,
                            IsAdmin = false,
                            PasswordHash = "$2a$11$lndSqgQXC5RexO5S6cxWIu8ffjLPpcNR7xQQq41y9aouMf584wm2u",
                            PinHash = "$2a$11$Xkgs2dzU4n/gjcB4Y/NU5OSVM5ws31xKLgi/6k9JdP/xV46V7I7NO",
                            RoleId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Username = "mark.tanaka"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333304"),
                            BranchId = new Guid("a1111111-a111-a111-a111-a11111111111"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Elena Rostova",
                            HourlyRate = 22.00m,
                            IsActive = true,
                            IsAdmin = false,
                            PasswordHash = "$2a$11$lndSqgQXC5RexO5S6cxWIu8ffjLPpcNR7xQQq41y9aouMf584wm2u",
                            PinHash = "$2a$11$Xkgs2dzU4n/gjcB4Y/NU5OSVM5ws31xKLgi/6k9JdP/xV46V7I7NO",
                            RoleId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Username = "purchaser.admin"
                        });
                });

            modelBuilder.Entity("Pos.Domain.Entities.Vendor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TaxId")
                        .IsUnique();

                    b.ToTable("Vendors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1111111-d111-d111-d111-d11111111111"),
                            ContactPerson = "Jane Smith",
                            Email = "vendor@globalfoods.com",
                            IsActive = true,
                            Name = "Global Foods Co.",
                            Phone = "0819876543",
                            TaxId = "0105551234599"
                        });
                });

            modelBuilder.Entity("Pos.Domain.Entities.VoidLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CashierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("VoidLogs");
                });

            modelBuilder.Entity("Pos.Domain.Entities.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsMainWarehouse")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("Warehouses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1111111-b111-b111-b111-b11111111111"),
                            BranchId = new Guid("a1111111-a111-a111-a111-a11111111111"),
                            IsMainWarehouse = true,
                            Name = "Main Warehouse"
                        });
                });

            modelBuilder.Entity("Pos.Domain.Entities.WarehouseInventory", b =>
                {
                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("WarehouseId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("WarehouseInventories");
                });

            modelBuilder.Entity("Pos.Domain.Entities.Attendance", b =>
                {
                    b.HasOne("Pos.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pos.Domain.Entities.CashierShift", b =>
                {
                    b.HasOne("Pos.Domain.Entities.User", "Cashier")
                        .WithMany()
                        .HasForeignKey("CashierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cashier");
                });

            modelBuilder.Entity("Pos.Domain.Entities.CouponUsage", b =>
                {
                    b.HasOne("Pos.Domain.Entities.Order", null)
                        .WithOne("CouponUsage")
                        .HasForeignKey("Pos.Domain.Entities.CouponUsage", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pos.Domain.Entities.LeaveRequest", b =>
                {
                    b.HasOne("Pos.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pos.Domain.Entities.MemberAiRecommendation", b =>
                {
                    b.HasOne("Pos.Domain.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pos.Domain.Entities.Product", "RecommendedProduct")
                        .WithMany()
                        .HasForeignKey("RecommendedProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("RecommendedProduct");
                });

            modelBuilder.Entity("Pos.Domain.Entities.MemberPromotion", b =>
                {
                    b.HasOne("Pos.Domain.Entities.Product", "FreeProduct")
                        .WithMany()
                        .HasForeignKey("FreeProductId");

                    b.Navigation("FreeProduct");
                });

            modelBuilder.Entity("Pos.Domain.Entities.Order", b =>
                {
                    b.HasOne("Pos.Domain.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Pos.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("Pos.Domain.Entities.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pos.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Pos.Domain.Entities.OrderPayment", b =>
                {
                    b.HasOne("Pos.Domain.Entities.Order", null)
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pos.Domain.Entities.PosTerminal", b =>
                {
                    b.HasOne("Pos.Domain.Entities.Branch", "Branch")
                        .WithMany("PosTerminals")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("Pos.Domain.Entities.Product", b =>
                {
                    b.HasOne("Pos.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Pos.Domain.Entities.ProductAssociation", b =>
                {
                    b.HasOne("Pos.Domain.Entities.Product", "PrimaryProduct")
                        .WithMany()
                        .HasForeignKey("PrimaryProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pos.Domain.Entities.Product", "RecommendedProduct")
                        .WithMany()
                        .HasForeignKey("RecommendedProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PrimaryProduct");

                    b.Navigation("RecommendedProduct");
                });

            modelBuilder.Entity("Pos.Domain.Entities.PurchaseOrder", b =>
                {
                    b.HasOne("Pos.Domain.Entities.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pos.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vendor");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Pos.Domain.Entities.PurchaseOrderItem", b =>
                {
                    b.HasOne("Pos.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pos.Domain.Entities.PurchaseOrder", null)
                        .WithMany("Items")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Pos.Domain.Entities.RoleRoutePermission", b =>
                {
                    b.HasOne("Pos.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Pos.Domain.Entities.ShiftSchedule", b =>
                {
                    b.HasOne("Pos.Domain.Entities.ShiftType", "ShiftType")
                        .WithMany()
                        .HasForeignKey("ShiftTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pos.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShiftType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pos.Domain.Entities.ShiftSwapRequest", b =>
                {
                    b.HasOne("Pos.Domain.Entities.ShiftSchedule", "RequestorShift")
                        .WithMany()
                        .HasForeignKey("RequestorShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RequestorShift");
                });

            modelBuilder.Entity("Pos.Domain.Entities.StockBatch", b =>
                {
                    b.HasOne("Pos.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pos.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Pos.Domain.Entities.User", b =>
                {
                    b.HasOne("Pos.Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId");

                    b.HasOne("Pos.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pos.Domain.Entities.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId");

                    b.Navigation("Branch");

                    b.Navigation("Role");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Pos.Domain.Entities.Warehouse", b =>
                {
                    b.HasOne("Pos.Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("Pos.Domain.Entities.WarehouseInventory", b =>
                {
                    b.HasOne("Pos.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pos.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Pos.Domain.Entities.Branch", b =>
                {
                    b.Navigation("PosTerminals");
                });

            modelBuilder.Entity("Pos.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Pos.Domain.Entities.Order", b =>
                {
                    b.Navigation("CouponUsage");

                    b.Navigation("Items");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Pos.Domain.Entities.PurchaseOrder", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
